name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Sample Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check this out
        run: |
          echo "These are the committers ${github.event.push.commits}"
