name: Lint
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flipt-io/validate-action@v0.1.0

